[package]
name = "libjose"
version = "0.1.0"
edition = "2021"
description = "A library for JOSE (JSON Object Signing and Encryption)"

[dependencies]
base64 = { version = "0.13", default-features = false }
miniz_oxide = { version = "0.5", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false }
url = { version = "2.2", default-features = false, features = ["serde"] }
zeroize = { version = "1.2", default-features = false, features = [
  "zeroize_derive",
] }

curve25519-dalek = { version = "3.0", default-features = false }
num-bigint-dig = { version = "0.7", default-features = false }
rand = { version = "0.8", default-features = false, features = ["getrandom"] }
rsa = { version = "0.6", default-features = false, features = ["pem", "std"] }
sha-1 = { version = "0.9", default-features = false }
subtle = { version = "2.4", default-features = false }

[dependencies.iota-crypto]
git = "https://github.com/iotaledger/crypto.rs"
rev = "0967233dd40ba562f575c2073cb8f4a22744e2d4"
default-features = false
features = [
  "aes",
  "aes-cbc",
  "aes-kw",
  "chacha",
  "ed25519",
  "hmac",
  "p256",
  "pbkdf",
  "random",
  "secp256k1",
  "sha",
  "x25519",
  "x448",
]

[features]
default = ["std"]

std = ["alloc", "serde/std", "serde_json/std"]

alloc = ["base64/alloc", "serde/alloc", "serde_json/alloc"]
test-rsa-enc = []
test-rsa-sig = []
