[package]
name = "identity-core"
version = "0.4.0"
edition = "2021"
description = "The core traits and types for the identity-rs library."

[dependencies]
base64 = { version = "0.13", default-features = false, features = ["std"] }
bs58 = { version = "0.4", default-features = false, features = ["std"] }
chrono = { version = "0.4", default-features = false, features = [
    "clock",
    "std",
] }
hex = { version = "0.4", default-features = false, features = ["std"] }
identity-diff = { version = "=0.4.0", path = "../identity-diff", default-features = false }
multibase = { version = "0.9", default-features = false, features = ["std"] }
roaring = { version = "0.8", default-features = false }
serde = { version = "1.0", default-features = false, features = [
    "std",
    "derive",
] }
serde_jcs = { version = "0.1", default-features = false }
serde_json = { version = "1.0", default-features = false, features = ["std"] }
strum = { version = "0.23", features = ["derive"] }
subtle = { version = "2.4", default-features = false }
thiserror = { version = "1.0", default-features = false }
typenum = { version = "1.13", default-features = false }
url = { version = "2.2", default-features = false, features = ["serde"] }
zeroize = { version = "1.2", default-features = false }

[dependencies.iota-crypto]
version = "0.9"
default-features = false
features = ["blake2b", "ed25519", "random", "sha"]

[dev-dependencies]
quickcheck = { version = "1.0" }
quickcheck_macros = { version = "1.0" }
rand = { version = "0.8" }
